### ISSUE TITLE
Getting group data doesn't seem to work

### ISSUE THREAD

**Issue by marcinkrzeminski** [palmiak/timber-acf-wp-blocks#16]
Hi,

I'm trying to access the group data. My group is called `engines`, but when I try to `{{ dump(fields.engines) }}` I get an empty string. Did you test it on your end with groups?

**Comment by palmiak** [comment]
Not sure to be honest, but I'll check it out. Thanks for the bug report.

czw., 16 sty 2020, 17:31 użytkownik Marcin Krzemiński <
notifications@github.com> napisał:

**Comment by marcinkrzeminski** [comment]
My bad :/. I have misconfigured the fields 😔
