### ISSUE TITLE
Improve documentation on changing location of blocks

### ISSUE THREAD

**Issue by montemartin** [palmiak/timber-acf-wp-blocks#2]
The fact that block files need to be in 'views/blocks' isn't mentioned in the documents. This needs to clarified and include an example of how to change the location if necessary. I spent a good bit of time trying to figure out why my blocks weren't showing up in the editor. I originally had the blocks in 'templates/blocks' which I finally realized wasn't correct. 

I still haven't gotten the plugin to work. So far I've tried: 

- Moving the blocks to 'views/blocks'
- Setting a filter on 'timber/acf-gutenberg-blocks-templates'
- Renaming the blocks location in the actual Composer file

At this point I think something else is blocking 'acf/init' because my PHP files aren't importing correctly either. I'm out of time for now, so once I have more time to debug I'll come back to this and figure it out.

**Comment by palmiak** [comment]
Could you provide me with your code so I can check it.

**Comment by palmiak** [comment]
Hi

I just tested it and it works ok so probably there is something missing in docs :)

The installation looked like this:
1. Install WP
2. Install Timber (from Composer)
3. Install ACF PRO 5.8 or newer
4. Create block in `THEME_FOLDER/views/blocks` - for example `test-block.twig`
5. Go to admin panel > custom fields
6. Add new group and there select `Show this field group if` as **block** and value as your block name

From this point you can add your own blocks :)

**Comment by palmiak** [comment]
I'm closing it for now - @montemartin if you would still need some help please reopen.
