### ISSUE TITLE
filenames with underscores are added to $paths with dashes

### ISSUE THREAD

**Issue by badabingbreda** [palmiak/timber-acf-wp-blocks#24]
When you add filenames that use underscores ( for instance "ylye_agenda_block.twig" ) the timber_acf_path_render() function returns the path as having dashes: "views/blocks/ylye-agenda-block.twig"

this results in the file not being found and thus no output.

I know it's because of ACF's requirement (Docs says this for the block's  'name' setting: A block name can only contain lowercase alphanumeric characters and dashes, and must begin with a letter) but took me a few minutes to debug so may be wise to add a note to timber-acf-wp-blocks docs.

**Comment by palmiak** [comment]
A good point. Maybe you would try to add a pull request for the docs?

**Comment by palmiak** [comment]
Thanks for the PR. I'm closing this. Great job.
