### ISSUE TITLE
InnerBlock

### ISSUE THREAD

**Issue by thisanimus** [palmiak/timber-acf-wp-blocks#27]
Any hints for how to enable InnerBlocks?

**Comment by palmiak** [comment]
Of course - check the SupportsJSX option (it should be mentioned in the docs)

**Comment by thisanimus** [comment]
Perfect! sorry, I overlooked that.  Thanks!

**Comment by thisanimus** [comment]
So I enable JSX in the header:
```
{#
...
  SupportsJSX: true
#}
```
and add the InnerBlock element in the template
```
<div class="{{ block.classes }}" data-{{ block.id }}>
	...
	<InnerBlocks allowedBlocks="['core/paragraph']" />
</div>
```
IS there something I'm missing?  I'm not seeing the inner blocks in the WP editor.

**Comment by palmiak** [comment]
Let's start with two basic question to rule out the obvious:
- do you have ACF 5.9?
- do you have have the 1.11.0 (or newer) timber-acf-wp-blocks version?

I just tested on WP 5.5 with stable ACF.

**Comment by thisanimus** [comment]
- wp: 5.5
- ACP Pro: 5.9
- "palmiak/timber-acf-wp-blocks": "^1.11"

**Comment by palmiak** [comment]
So it should work perfectly - I used this as a block:
```
{#
  Title: wrapper
  Description: Wrapper
  Category: formatting
  Icon: admin-comments
  Keywords: link
  Mode: preview
  PostTypes: post
  SupportsMode: false
  SupportsMultiple: true
  SupportsAlign: true
  SupportsJSX: true
#}

<div class="wrapper">
	<h1>Some test</h1>
        <InnerBlocks  />
</div>
```

also it may be caused by the fact the without block inside it may collapse to 0px - try adding some min-height for moment or something like this.

**Comment by thisanimus** [comment]
Ok, got it working.  Thanks

**Comment by palmiak** [comment]
Great to hear that :D Can you share what was the reason of your problem?

**Comment by thisanimus** [comment]
2 things:
1. Header "mode: edit" causes the 0-height thing. changing to preview fixes that.
2. Passing allowedBlocks breaks things.  I could not get it working with any of these:

<InnerBlocks allowedBlocks={['core/paragraph']} />

<InnerBlocks allowedBlocks={{['core/paragraph']}} />

<InnerBlocks allowedBlocks=['core/paragraph'] />

<InnerBlocks allowedBlocks={'core/paragraph'} />

{% set allowed = ['core/paragraph'] %}
<InnerBlocks allowedBlocks={{ allowed }} />


{% set allowed = "{['core/paragraph']}" %}
<InnerBlocks allowedBlocks={{ allowed }} />

**Comment by palmiak** [comment]
Here you go
```<InnerBlocks
allowedBlocks="{{ ['core/image', 'core/paragraph'] | json_encode() | escape('html_attr') }}"
/>```

maybe I'll add a new Twig filter called prepare_block_attr. so could just run `allowedBlocks="{{ ['core/image', 'core/paragraph'] | prepare_block_attr }}"`

**Comment by Wndworks** [comment]
I try to make this work with the template attribute to prefill the block, but I can't make it work. The allowedBlocks is working tho. Any ideas?

<InnerBlocks
	template="{{ ['core/image', 'core/image'] | json_encode() | escape('html_attr') }}"
	allowedBlocks="{{ ['core/image'] | json_encode() | escape('html_attr') }}"
/>
