### ISSUE TITLE
The use statement with non-compound name has no effect

### ISSUE THREAD

**Issue by chilly86** [palmiak/timber-acf-wp-blocks#30]
Hi,

After updating the package I got these warnings:

Warning: The use statement with non-compound name 'DirectoryIterator' has no effect in ***/vendor/palmiak/timber-acf-wp-blocks/timber-acf-wp-blocks.php on line 8

Warning: The use statement with non-compound name 'FilesystemIterator' has no effect in ***/vendor/palmiak/timber-acf-wp-blocks/timber-acf-wp-blocks.php on line 9

Warning: The use statement with non-compound name 'RecursiveDirectoryIterator' has no effect in ***/vendor/palmiak/timber-acf-wp-blocks/timber-acf-wp-blocks.php on line 10

Environment:
OS: Ubuntu
PHP version: 7.2.32

Please remove the mentioned 3 use statements as you are in the global namespace, therefore you don't need them.

Thanks a lot!

**Comment by WRCarlile** [comment]
I am seeing this as well

**Comment by palmiak** [comment]
I just got back from vacations. I'll try to fix this ASAP.

śr., 9 wrz 2020, 02:00 użytkownik Ryan Carlile <notifications@github.com>
napisał:

**Comment by palmiak** [comment]
Just release the new version that should fix this bug.

**Comment by chilly86** [comment]
Thank you very much for the fix! It seems okay. Keep up the good work!
