### ISSUE TITLE
Pass options to innerblocks

### ISSUE THREAD

**Issue by landwire** [palmiak/timber-acf-wp-blocks#32]
Hi there,
I am having trouble passing options to an innerBlock. Do you have any idea, how to do it? Or would it have to be an option in the top area, where all the options are passed to the block?

I tried this in my template and many other variations, but nothing worked.

`
{% autoescape false %}
      <InnerBlocks allowedBlocks="{{ "['core/paragraph']" | json_encode }}" />
{% endautoescape %}
`
I get this: string(21) ""['core\/paragraph']""

Problem is likely some escaping, but I do not know.

**Comment by palmiak** [comment]
Take a look here - https://github.com/palmiak/timber-acf-wp-blocks/issues/27

I think I'll add a Twig filter to make i simpler :)

**Comment by landwire** [comment]
Maciej,
thanks so much! I tried escape but not escape(‘html_attributes’).

Also good to know about the 0 height problem!
