### ISSUE TITLE
filter for template directory

### ISSUE THREAD

**Issue by pixelstorm** [palmiak/timber-acf-wp-blocks#37]
Sorry.. this is not an issue, its just a question.
How do we use this filter to set a different template directory? For some reason there is no example in the docs
https://palmiak.github.io/timber-acf-wp-blocks/#/using-example

timber/acf-gutenberg-blocks-templates - path where you blocks are kept - default: [ 'views/blocks' ]

**Comment by lukethacoder** [comment]
```php
add_filter('timber/acf-gutenberg-blocks-templates', function () {
  return ['views/not-blocks'];
});
```

should do the trick. but I can't even get the blocks working myself https://github.com/palmiak/timber-acf-wp-blocks/issues/38

**Comment by pixelstorm** [comment]
thats great thanks. the blocks are working for me. as per the docs. Just adding the "block comments" to the file produces a block in gutenberg.
