### ISSUE TITLE
Blocks not recognised by ACF or Gutenberg?

### ISSUE THREAD

**Issue by lukethacoder** [palmiak/timber-acf-wp-blocks#38]
Steps to reproduce:

- Install `timber-acf-wp-blocks` via Composer
- Add a block to `THEME/views/blocks/my-block.twig`
- no blocks in WP?

I feel like I am missing something somewhere as I cannot get these blocks to show in either the ACF `Add New Field Group` page or on any page with the Gutenberg block selector.

Have had a crack at changing the blocks directory using `timber/acf-gutenberg-blocks-templates` but still no luck.

Using a very simple bit of code to test the blocks are working:

```twig
{#
  Title: hello world twig.
  Description: hello world twig.
  Category: formatting
  Icon: admin-comments
  Keywords: twig "hello world"
  Mode: edit
  Align: left
  PostTypes: page post
  SupportsAlign: left right
  SupportsMode: false
  SupportsMultiple: false
#}

<blockquote class="{{ classes }}" data-{{ block.id }}>
    <p>{{ fields.title }}</p>
    <cite>
      <span>{{ fields.another_field }}</span>
    </cite>
</blockquote>

<style type="text/css">
  [data-{{ block.id }}] {
    background: {{ fields.background_color }};
    color: {{ fields.text_color }};
  }
</style>
```

![twig file and theme folder structure](https://user-images.githubusercontent.com/13529535/98108125-99b93180-1eef-11eb-973d-607b5182b7f2.png)

![empty gutenberg block selector](https://user-images.githubusercontent.com/13529535/98108174-ad649800-1eef-11eb-9d9a-1a54f2d66259.png)

![no blocks types exist in acf 'Add New Field Group'](https://user-images.githubusercontent.com/13529535/98108058-827a4400-1eef-11eb-8252-3c9f16a70ce6.png)

**Comment by palmiak** [comment]
Did you installed this with the theme's composer or some global site-one?

**Comment by lukethacoder** [comment]
![image](https://user-images.githubusercontent.com/13529535/98109650-ffa6b880-1ef1-11eb-9446-94f04ed46056.png)

its installed at a global site level. should it be added at the theme level?

**Comment by palmiak** [comment]
Yes - I really have to create a plugin version so it could be installed
globally 😀

śr., 4 lis 2020, 13:04 użytkownik Luke Secomb <notifications@github.com>
napisał:

**Comment by lukethacoder** [comment]
Makes sense after checking out the source code. Thanks for the swift reply.
