### ISSUE TITLE
Access $context['post']

### ISSUE THREAD

**Issue by thisanimus** [palmiak/timber-acf-wp-blocks#39]
Not really an issue, just a question. Is there a way to access the current post data from within a block?  Currently doing something like {{ post.title }} inside a block returns nothing.

**Comment by palmiak** [comment]
You would probably have to use one of the filters to pass the variable
inside.

timber/acf-gutenberg-blocks-data

wt., 24 lis 2020, 19:34 użytkownik Andrew Hale <notifications@github.com>
napisał:

**Comment by thisanimus** [comment]
Perfect, got it, thanks!

**Comment by geoffyuen** [comment]
@thisanimus Can you post your code on how you did this?

**Comment by thisanimus** [comment]
@geoffyuen 

```
add_filter( 'timber/acf-gutenberg-blocks-data', function( $context ){
    $context['post'] = Timber::get_post();
    return $context;
} );
```
