### ISSUE TITLE
Disappear from Gutenberg after WP 5.6 update

### ISSUE THREAD

**Issue by erimeilis** [palmiak/timber-acf-wp-blocks#42]
In some cases they disappear at all (even from frontend), in some cases it still works, but no chance to add new ones as they're not discoverable through Gutenberg menu.

**Comment by palmiak** [comment]
I also use WP 5.6 so it must something related to  your hosting or website. Let me think how to debug this.

**Comment by erimeilis** [comment]
Hello! ACF Pro updated to 5.9.4 and, seems, it closed the issue
