### ISSUE TITLE
Composer install not working as expected from release 1.14 to 1.15

### ISSUE THREAD

**Issue by dylanjameswagner** [palmiak/timber-acf-wp-blocks#46]
It looks like between release 1.14 and 1.15 you have converted this to a WordPress mu-plugin.

Previously it would install into a `vendor` directory in my theme root. I am running composer at the theme level and when I run the install for your package `composer require "palmiak/timber-acf-wp-blocks"` it installs in a directory in my theme `wp-content/mu-plugin/timber-acf-wp-blocks`, which is misplaced because I am not running composer at the site root, I am running it only at the theme level.

I was using version 1.9, I am currently testing version 1.14 so far my blocks appear to work as expected I have yet to test any new features in the later versions.

If you are going to create this as a plugin can you maintain it as two separate repos, this one as it was, and another one as a plugin? If you are putting your energy into creating/maintaining a WordPress plugin will there be a plugin updates notifications within WordPress?

**Comment by palmiak** [comment]
Hi, my mistake. I marked 1.15 as pre release, but I see packagist used is a
normal release.

Now it should be ok. 1.14 is the last version.

wt., 2 lut 2021, 17:34 użytkownik Dylan James Wagner <
notifications@github.com> napisał:

**Comment by dylanjameswagner** [comment]
Tested the require receives 1.14. Thank you
