### ISSUE TITLE
Allow keywords to contain multi-word strings

### ISSUE THREAD

**Issue by hacknug** [palmiak/timber-acf-wp-blocks#5]
From core, `keywords` array can only contain a maximum of three items (it can technically contain whatever but only the first three items are used).

Instead of using spaces to split the string, a comma should be used. That would allow for multi-word strings which is 100% compatible with core.

**Comment by palmiak** [comment]
Great idea @hacknug  I just have to think how to do this without breaking backward compatibility.

So I think it would be better to allow users to use `"word word"` or `'word word`. Than we would still use spaces.

**Comment by palmiak** [comment]
@hacknug checkout the branch https://github.com/palmiak/timber-acf-wp-blocks/tree/quotes_in_keywords . You can use keywords with double quotes.

I think it's ok on my end but it would be great if you could check it before I'll merge it to master.

**Comment by hacknug** [comment]
Regex doesn't work correctly. It still captures both opening and closing quotes. Besides that, works fine :+1:

**Comment by palmiak** [comment]
Fixed it at last. Now it looks ok. I'll merge it into the master during the weekend

**Comment by hacknug** [comment]
Didn't know about `str_getcsv` 😮  Thank you!

**Comment by palmiak** [comment]
I also learned about it just now :)
