### ISSUE TITLE
Conflict with Gutenberg "Read More" Block option to hide excerpt

### ISSUE THREAD

**Issue by errand** [palmiak/timber-acf-wp-blocks#51]
When using the "Read More" Block option to hide excerpt, Timber uses extra function to trim the content

`	protected function content_handle_no_teaser_block( $content ) {
		if ( strpos($content, '"noTeaser":true') !== false ) {
			$arr = explode('', $content);
			return $arr[1];
		}
		return $content;
	}`
[Post](https://github.com/timber/timber/blob/0a98324a5574484b4b9ccab1fec5fba7abeb20cd/lib/Post.php#L1244)

But after rendering Custom block remain as a comment.
![image](https://user-images.githubusercontent.com/1334432/121004403-52519700-c797-11eb-954d-6762cf9fab36.png)

https://github.com/timber/timber/issues/2337

**Comment by palmiak** [comment]
Two questions:
- first of all - is this Timber or timber-acf-wp-block related? In short - if you would create a custom with ACF without this add-on will there still be an error or not? If it's Timber related - than post an issue there. If they will fix it than it should start working correctly here too.
- could you write a step by step how to reproduce - of course if it's timber-acf-wp-block related

**Comment by errand** [comment]
- I created the custom block using Timber only and yes, the probles is not with your plugin. Thank you for the idea.
- If one day you'd like to check the issue, it's very easy to reprocduce. Install WP, Timber, add ACF block as plugin, add block to the post, add Read more tag  with "hide teaser on the post page" checkbox on. Publish and you'll see that ACF block is commented and not rendering
