### ISSUE TITLE
Working with ACF 6.0.2?

### ISSUE THREAD

**Issue by mc72** [palmiak/timber-acf-wp-blocks#63]
Does this still work with ACF 6.0.2?  I just upgraded my ACF and am now getting errors like: "Your site doesn’t include support for the "acf/latest-news" block. You can leave this block intact or remove it entirely."  And the blocks are on longer accessible in ACF and not rendering on the front end.

But I am a newbieish to this addon and not sure if it's site specific or just no longer supported?  (I did have it working in v 5.XXX)

**Comment by palmiak** [comment]
I will have to check it out.

In theory - the legacy block API should work normally. At least according
to this article
https://www.advancedcustomfields.com/resources/acf_register_block_type/



pt., 30 wrz 2022, 21:59 użytkownik Mike Ciccone ***@***.***>
napisał:

**Comment by palmiak** [comment]
Just tested and everything seems to work without any problem.

**Comment by mc72** [comment]
Ok, it's a problem on my end.  Thank you for testing.
