### ISSUE TITLE
Wordpress not there yet, when code checks for wordpress

### ISSUE THREAD

**Issue by landwire** [palmiak/timber-acf-wp-blocks#9]
Hi there,
I followed your instructions, but somehow the autoloader seems to load the package too early and wordpress is not available yet. I have a "normal" roots.io bedrock setup. Is there something I have to change about the loading order or anything?

To test, I made your code into a plugin and then it works fine. But I would prefer to use the composer package.
Thanks for any help,
Sascha

**Comment by palmiak** [comment]
Hi, I also use it with bedrock. One question though - do you use it with theme composer or bedrock's composer?

I always add it to the theme's composer.

**Comment by landwire** [comment]
Ah! That might be the problem. Added it to the bedrock composer! Will try it with the themes composer and give some feedback.
Thank you for the quick reply!

**Comment by landwire** [comment]
My bad!

Works like a charm now and it clearly says in the documentation:
Run the following in your Timber-based theme directory:
composer require "palmiak/timber-acf-wp-blocks"

Thanks again for your help and the code!

**Comment by drzraf** [comment]
Since this plugin does not rely upon assets (that would not load from /vendor/ directory), it does not need to be a dependency of the theme? Any way this could work from Bedrock's autoload?

**Comment by palmiak** [comment]
Hi @drzraf 

I will be creating a plugin version of this library (#12) so you'll be able to add this to Bedrock's main composer. As I'll automate the process I can also create an mu-plugin so it will always be active. I hope I'll do this during the upcoming two weeks.

**Comment by mortensassi** [comment]
Hi @palmiak any news on this? I can't get this plugin to work with my bedrock installation.

I have installed and put the plugin in the mu-plugins folder which also gets displayed in the backend
However, in my Class i am making usage of some of your filters, like redefining the path:

```php
public function twigGutenbergDirectory()
    {
        return ['templates/blocks'];
    }
```

And the blocks won't get displayed. However, when i install the plugin in my theme and autoload it, then it works..
